### ISSUE TITLE
Setup Github PR Route

### ISSUE THREAD

**Issue by wlawt** [MLH-Fellowship/0.2.2-github-automator#3]
- [ ] Be able to GET request Github API

- Only keep the data for the following
- [ ] User
- [ ] Reviewer
- [ ] Podname
- [ ] Created_at
- [ ] Upated_at

**Comment by wlawt** [comment]
cors error that I have in Sheet.jsx

**what I've tried**
I've tried adding headers to the axios, but it doesn't work
`
headers { 
    "Access-Control-Allow-Origin": "*" 
}
`

`componentWillMount() {
        axios.get("https://api.github.com/users/MLH-Fellowship/repos").then(res => {
            for (var i = 0; i < res.data.length; i++) {
                this.setState({ all_repos: this.state.all_repos.concat(res.data[i].name) })
            }

            this.state.all_repos.map(repo => {
                axios.get(`https://api.github.com/repos/MLH-Fellowship/${repo}/pulls?state=open`).then(pull_res => {
                    const repo_status = {
                        name: repo,
                        assignee: pull_res.assignee ? null : pull_res.assignees,
                        reviewers: pull_res.requested_reviewers,
                        created_at: pull_res.created_at,
                        updated_at: pull_res.updated_at
                    }

                    this.setState({ all_prs: this.state.all_prs.concat(repo_status) })
                })
            })
        })
    }`

**Comment by yahengsu** [comment]
is the error still `blocked by CORS policy: Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers in preflight response.`

**Comment by wlawt** [comment]
yup i also got that as well

**Comment by zzj0402** [comment]
Try disable web security. Also make sure GitHub.com allows CORS request

**Comment by ianjennings** [comment]
Try serving through ngrok (gives your local host a domain name) and updated the GitHub application to use the ngrok domain: https://ngrok.com

**Comment by wlawt** [comment]
closing the issue, atm not using github API (but thanks @ianjennings for pointing out the github rate error : )
